### ISSUE TITLE
yamcs-scos2k upgrade to latest yamcs core

### ISSUE THREAD

**Issue by WilfridGonzalez** [yamcs/yamcs-scos2k#3]
Latest release of yamcs-scos2k is built upon yamcs 5.4.1.
It is not able to build on the latest realease of yamcs core (which is 5.7.10 as for now)

Is there a plan to fix the build and upgrade this loader to the latest release ?

**Comment by xpromache** [comment]
I updated it work with yamcs 5.7.9 which is the latest one released.
Please let me know if you have problems.

**Comment by WilfridGonzalez** [comment]
Hello,
Thanks for your update, it worked nicely with the 5.7.10-SNAPSHOT I had locally built and allowed me to go further in my testings.
Just to give you some context, I'm trying to load a full MIB extract from an actual spacecraft program database in order to evaluate the YAMCS toolchain.
I encountered some of the limitations raised in the other issue  #1 Load data opened some time ago, like the support for CDF_ELTYPE=F. For this I had to patch the cdf.dat file and switched the type to E for a smooth parsing.
My main issue was with deduced parameter types and variable length arguments to TCs : some of the TC arguments are defined with  CDF_ELLEN=0 (varialble length) and the CDF_PNAME is pointing in cpc.dat to parameter of type deduced (PTC=11). I had to force 1 bit length and ptc/pfc=2/1 for the parsing to work.
Through this temporary hack of my mib files, I was able to decommute a TM 3,25 packet in the packet viewer

**Comment by xpromache** [comment]
It's a long time I have not looked at a SCOS2k MIB so cannot say much without spending time to dig the details.

But  are you able to share a minimum reproducible test case: 
- MIB files
- binary packet to be decoded + expected parameter values (for TM) 
- command name + arguments + expected command binary packet (for TC)

**Comment by WilfridGonzalez** [comment]
In order to make rapid progress in my testings, I have used the actual spacecraft database extracts, which I'm not allowed to make public.
I fully agree with you that the right approach is to contribute to test data on a limited but representative case.
I will need some time to get further into the use of YAMCS framework and try setting up the minimal test case you describe.
Thanks for your valuable help

**Comment by WilfridGonzalez** [comment]
As far as I am concerned, this issue can be closed : the updated source code works nicely with the last snapshot version of YAMCS framework.
For other limitations/issues that were or will be identified by my testings, I propose to open dedicated issues.
Thx for your help

**Comment by xpromache** [comment]
Ok. If you can provide some MIB files  reproducing the problems you report,
that would be great.

**Comment by WilfridGonzalez** [comment]
Sure, working on it but will take some time

**Comment by xpromache** [comment]
Closing this issue as the original problem (upgrade yamcs-scos2k to the latest yamcs) has been solved.
